# Generated by Django 5.1.1 on 2024-11-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_audiencia_ubicaciones_comunes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicaciones_comunes',
            name='nombre_ubicacion',
        ),
        migrations.AddField(
            model_name='ubicaciones_comunes',
            name='direccion_ubicacion',
            field=models.CharField(max_length=350, null=True, verbose_name='direccion'),
        ),
    ]
