# Generated by Django 5.1.1 on 2024-11-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_ubicaciones_comunes_nombre_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinas',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='subdisciplinas',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'Subdisciplinas'},
        ),
        migrations.AlterModelTable(
            name='disciplinas',
            table='Disciplinas',
        ),
        migrations.AlterModelTable(
            name='subdisciplinas',
            table='Subdisciplinas',
        ),
    ]
