# Generated by Django 5.1.1 on 2024-11-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_disciplinas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones_comunes',
            name='name_ubication',
            field=models.CharField(max_length=100, null=True, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='ubicaciones_comunes',
            name='direccion_ubicacion',
            field=models.CharField(max_length=350, null=True, verbose_name='Direccion'),
        ),
    ]
