# Generated by Django 5.1.1 on 2024-11-12 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_rename_name_ubication_ubicaciones_comunes_nombre_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_redSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_redSocial', models.CharField(max_length=80, verbose_name='Red Social')),
            ],
            options={
                'verbose_name': 'CatalogoRedSocial',
                'verbose_name_plural': 'CatalogoRedesSociales',
                'db_table': 'CatalogoRedesSociales',
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace_redSocial', models.CharField(max_length=500, verbose_name='enlace')),
                ('id_redSocial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redsocial', to='catalogo.cat_redsocial')),
            ],
            options={
                'verbose_name': 'RedSocial',
                'verbose_name_plural': 'RedesSociales',
                'db_table': 'RedSocial',
            },
        ),
    ]
