# Generated by Django 5.1.1 on 2024-11-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_cat_redsocial_redsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='id_redSocial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.cat_redsocial'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image_actor', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Image Perfil')),
                ('nombre_Actor', models.CharField(max_length=80, verbose_name='Nombres')),
                ('primero_apellido_Actor', models.CharField(max_length=80, verbose_name='Primer Apellido')),
                ('segundo_apellido_Actor', models.CharField(max_length=80, verbose_name='Segundo Apellido')),
                ('biografia_Actor', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('correo_publico_Actor', models.CharField(blank=True, max_length=100, verbose_name='Correo Publico')),
                ('correo_privado_actor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo Privado')),
                ('Telefono_publico_Actor', models.CharField(blank=True, max_length=10, verbose_name='Telefono Publico')),
                ('Telefono_privado_actor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono Privado')),
                ('id_subdisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdisciplinas', to='catalogo.subdisciplinas')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actores',
                'db_table': 'Actor',
            },
        ),
        migrations.AddField(
            model_name='redsocial',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Redes_Sociales', to='catalogo.actor'),
        ),
        migrations.CreateModel(
            name='publicacionObras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen_publicacion', models.ImageField(upload_to='imagenes/', verbose_name='Imagen Portada')),
                ('titulo_publicacion', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion_publicacion', models.TextField(verbose_name='Descripcion')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha Publicacion')),
                ('id_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Publicacion_Obra', to='catalogo.actor')),
            ],
            options={
                'verbose_name': 'PublicacionObra',
                'verbose_name_plural': 'PublicacionObras',
                'db_table': 'PublicacionObras',
            },
        ),
    ]
