# Generated by Django 5.1.1 on 2024-11-13 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_redsocial_id_redsocial_actor_redsocial_actor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen_escuela', models.ImageField(upload_to='imagenes/', verbose_name='Imagen portada')),
                ('nombre_escuela', models.CharField(max_length=100, verbose_name='Nombre Escuela')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('telefono_escuela', models.CharField(max_length=10, verbose_name='Telefono')),
                ('correo_escuela', models.CharField(max_length=100, verbose_name='Correo')),
                ('hora_atencion', models.CharField(max_length=50, verbose_name='Horario Atencion')),
                ('paginaOficial', models.URLField(blank=True, null=True, verbose_name='Pagina Oficial')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'db_table': 'Escuelas',
            },
        ),
        migrations.CreateModel(
            name='Imagenes_publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='imageneURL')),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenPublicaciones', to='catalogo.publicacionobras')),
            ],
            options={
                'verbose_name': 'imagenPublicacion',
                'verbose_name_plural': 'imagenPublicaciones',
                'db_table': 'ImagenPublicaciones',
            },
        ),
        migrations.CreateModel(
            name='publicacionEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen_publicacion', models.ImageField(upload_to='imagnes/')),
                ('titulo_publicacion', models.CharField(max_length=150, verbose_name='Titulo')),
                ('descripcion_publicacion', models.TextField(verbose_name='Descripcion')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha Publicacion')),
                ('precio_evento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio por Persona')),
                ('puntoVenta', models.BooleanField(default=False)),
                ('enlace_venta', models.URLField(blank=True, null=True, verbose_name='URL del punto de venta')),
                ('id_clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion', to='catalogo.audiencia')),
            ],
            options={
                'verbose_name': 'PublicacionEvento',
                'verbose_name_plural': 'PublicacionEventos',
                'db_table': 'PublicacionEvento',
            },
        ),
    ]
