# Generated by Django 5.1.1 on 2024-11-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_escuelas_imagenes_publicaciones_publicacioneventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacioneventos',
            name='url_imagen_publicacion',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
