# Generated by Django 5.1.1 on 2024-11-14 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_alter_publicacioneventos_url_imagen_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='id_escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.escuelas'),
        ),
    ]
