# Generated by Django 5.1.1 on 2024-11-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_actor_id_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuelas',
            name='ubicacion_escuela',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicacion'),
        ),
    ]
