# Generated by Django 5.1.1 on 2024-11-19 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_escuelas_ubicacion_escuela'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='primero_apellido_Actor',
            new_name='primer_apellido_Actor',
        ),
    ]
