# Generated by Django 5.1.1 on 2024-11-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_remove_redsocial_id_actor_redsocial_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
