# Generated by Django 5.1.1 on 2024-11-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_alter_redsocial_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_redsocial',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_redes/'),
        ),
    ]
