# Generated by Django 5.1.1 on 2024-11-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0021_cat_redsocial_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_redsocial',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos_redes/'),
        ),
    ]
