# Generated by Django 5.1.1 on 2024-11-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0024_localidad_escuelas_id_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='Telefono_privado_actor',
            field=models.CharField(blank=True, default='...', max_length=10, null=True, verbose_name='Telefono Privado'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='Telefono_publico_Actor',
            field=models.CharField(blank=True, default='...', max_length=10, null=True, verbose_name='Telefono Publico'),
        ),
        migrations.RemoveField(
            model_name='actor',
            name='id_escuela',
        ),
        migrations.AddField(
            model_name='actor',
            name='id_escuela',
            field=models.ManyToManyField(blank=True, null=True, to='catalogo.escuelas'),
        ),
    ]
