# Generated by Django 5.1.1 on 2024-11-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0025_alter_actor_telefono_privado_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id_escuela',
            field=models.ManyToManyField(blank=True, related_name='actores', to='catalogo.escuelas'),
        ),
    ]
