# Generated by Django 5.1.1 on 2024-11-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0026_alter_actor_id_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacioneventos',
            name='id_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.actor', verbose_name='Actor'),
        ),
    ]
