# Generated by Django 5.1.1 on 2024-11-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0027_publicacioneventos_id_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacioneventos',
            name='id_disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.disciplinas', verbose_name='Categoria Disciplina'),
        ),
    ]
