# Generated by Django 5.1.1 on 2024-11-24 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0029_publicacionobras_id_ubicacionescomunes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacionobras',
            name='id_ubicacionesComunes',
        ),
        migrations.AddField(
            model_name='publicacioneventos',
            name='id_ubicacionesComunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ubicaciones', to='catalogo.ubicaciones_comunes', verbose_name='Ubicacion'),
        ),
    ]
