# Generated by Django 5.1.1 on 2024-11-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0032_ubicaciones_comunes_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacioneventos',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='publicacioneventos',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
