# Generated by Django 5.1.1 on 2024-11-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0033_remove_publicacioneventos_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacioneventos',
            name='publicacion_aprobada',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
    ]
