# Generated by Django 5.1.1 on 2024-12-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0034_publicacioneventos_publicacion_aprobada'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionobras',
            name='publicacion_aprobada',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='publicacioneventos',
            name='publicacion_aprobada',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
    ]
