# Generated by Django 5.1.1 on 2024-12-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0035_publicacionobras_publicacion_aprobada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacioneventos',
            name='fecha_creacion_publicacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AddField(
            model_name='publicacionobras',
            name='fecha_creacion_publicacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creacion'),
        ),
    ]
