# Generated by Django 5.1.1 on 2024-12-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0036_publicacioneventos_fecha_creacion_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='tipo_usuario',
            field=models.CharField(choices=[('actor', 'Actor'), ('administrador', 'Administrador'), ('ambos', 'Ambos')], default='actor', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
