# Generated by Django 5.1.1 on 2025-01-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0037_actor_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='correo_publico_Actor',
            field=models.CharField(blank=True, default='....', max_length=100, null=True, verbose_name='Correo Publico'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nombre_Actor',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='primer_apellido_Actor',
            field=models.CharField(max_length=80, null=True, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='segundo_apellido_Actor',
            field=models.CharField(max_length=80, null=True, verbose_name='Segundo Apellido'),
        ),
    ]
