# Generated by Django 5.1.1 on 2025-01-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0038_alter_actor_correo_publico_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
