# Generated by Django 5.1.1 on 2025-01-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0039_actor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionobras',
            name='id_Disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Categoria', to='catalogo.disciplinas'),
        ),
    ]
