# Generated by Django 5.1.1 on 2025-01-10 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0040_publicacionobras_id_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionobras',
            name='id_Escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Publicacion_Escuela', to='catalogo.escuelas'),
        ),
        migrations.AddField(
            model_name='publicacionobras',
            name='tipo_publicacion',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tipo Publiacion'),
        ),
    ]
