# Generated by Django 5.1.1 on 2025-01-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0041_publicacionobras_id_escuela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionobras',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Publicacion'),
        ),
    ]
