# Generated by Django 5.1.1 on 2025-01-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0042_alter_publicacionobras_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacioneventos',
            name='puntoVenta',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('digital', 'Digital'), ('ambos', 'Ambos')], default='presencial', max_length=50, null=True, verbose_name='Punto de Venta'),
        ),
    ]
