# Generated by Django 5.1.1 on 2025-01-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0043_alter_publicacioneventos_puntoventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacioneventos',
            name='precio_evento',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Precio por Persona'),
        ),
    ]
