# Generated by Django 5.1.1 on 2025-01-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0046_alter_actor_url_image_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_redsocial',
            name='nombre_redSocial',
            field=models.CharField(max_length=30, verbose_name='Red Social'),
        ),
    ]
