# Generated by Django 5.1.1 on 2025-01-16 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0047_alter_cat_redsocial_nombre_redsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id_subdisciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdisciplinas', to='catalogo.subdisciplinas'),
        ),
    ]
