# Generated by Django 5.1.1 on 2025-01-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0048_alter_actor_id_subdisciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes_publicaciones',
            name='indice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
